[workspace]
members = ["grpc-webrtc-rsbridge", "reachy-api", "simulator"]
resolver = "2"

[workspace.package]
version = "1.0.0"
edition = "2021"
authors = ["Pollen Robotics"]
description = "Bridge SDK server (grpc) through WebRTC"
documentation = "https://www.pollen-robotics.com"
